"""Explicit business entities that replace new uses of the legacy ``picks`` table.

The legacy table remains readable for compatibility. New model, contest,
sportsbook, adjustment, revision, and audit writes belong in these append-only
services so that each concept has one auditable meaning.
"""

from business_entities.adjustments import (
    ManualAdjustment,
    list_manual_adjustments,
    record_manual_adjustment,
)
from business_entities.audits import PickAudit, list_pick_audits, record_pick_audit
from business_entities.cards import (
    CardRevision,
    ContestCard,
    ContestPick,
    add_contest_pick,
    create_contest_card,
    list_contest_picks,
    record_card_revision,
)
from business_entities.common import BusinessEntityConflictError, BusinessEntityError
from business_entities.contextual_adjustments import (
    AdjustmentImpact,
    CardAdjustmentPolicyAssignment,
    ManualAdjustmentPolicy,
    PickAdjustmentItem,
    PickAdjustmentSnapshot,
    RecordedManualAdjustmentPolicy,
    adjusted_confidence,
    adjustment_impact,
    adjustment_policy_from_card,
    assign_card_adjustment_policy,
    get_card_adjustment_policy,
    get_pick_adjustment_snapshot,
    list_card_adjustment_snapshots,
    list_pick_adjustment_items,
    record_pick_adjustment_snapshot,
    register_manual_adjustment_policy,
)
from business_entities.full_card import (
    CardCompletenessReport,
    FullCardError,
    FullCardPolicy,
    FullCardResult,
    IncompleteCardError,
    generate_full_card,
    inspect_full_card,
    validate_full_card,
)
from business_entities.modeling import (
    ModelPrediction,
    ModelRun,
    record_model_prediction,
    record_model_run,
)
from business_entities.ranking import (
    CardPolicyAssignment,
    ConfidenceRankingPolicy,
    ContestRankingPolicy,
    assign_card_ranking_policy,
    get_card_ranking_policy,
    register_confidence_ranking_policy,
)
from business_entities.refreshes import (
    CardRefreshPolicy,
    CardRefreshRevision,
    CardRevisionPickChange,
    DailyRefreshError,
    DailyRefreshPolicy,
    DailyRefreshResult,
    get_card_refresh_policy,
    get_card_refresh_revision,
    list_card_revision_pick_changes,
    refresh_full_card,
    register_daily_refresh_policy,
)
from business_entities.reproducibility import (
    CardRunManifest,
    ContestSelectionPolicy,
    ReproducibilityError,
    adjustment_history_sha256,
    get_card_run_manifest,
    get_contest_selection_policy,
    list_card_adjustment_history,
    reproduce_card,
)
from business_entities.wagering import (
    SportsbookRecommendation,
    record_sportsbook_recommendation,
)


__all__ = [
    "BusinessEntityConflictError",
    "BusinessEntityError",
    "AdjustmentImpact",
    "CardAdjustmentPolicyAssignment",
    "CardRevision",
    "CardCompletenessReport",
    "CardPolicyAssignment",
    "CardRunManifest",
    "CardRefreshPolicy",
    "CardRefreshRevision",
    "CardRevisionPickChange",
    "ConfidenceRankingPolicy",
    "ContestCard",
    "ContestPick",
    "ContestRankingPolicy",
    "ContestSelectionPolicy",
    "DailyRefreshError",
    "DailyRefreshPolicy",
    "DailyRefreshResult",
    "ManualAdjustment",
    "ManualAdjustmentPolicy",
    "ModelPrediction",
    "ModelRun",
    "PickAudit",
    "PickAdjustmentItem",
    "PickAdjustmentSnapshot",
    "RecordedManualAdjustmentPolicy",
    "SportsbookRecommendation",
    "ReproducibilityError",
    "FullCardError",
    "FullCardPolicy",
    "FullCardResult",
    "IncompleteCardError",
    "add_contest_pick",
    "adjusted_confidence",
    "adjustment_impact",
    "adjustment_policy_from_card",
    "adjustment_history_sha256",
    "assign_card_ranking_policy",
    "assign_card_adjustment_policy",
    "create_contest_card",
    "generate_full_card",
    "get_card_ranking_policy",
    "get_card_adjustment_policy",
    "get_card_refresh_policy",
    "get_card_refresh_revision",
    "get_card_run_manifest",
    "get_contest_selection_policy",
    "inspect_full_card",
    "get_pick_adjustment_snapshot",
    "list_card_adjustment_snapshots",
    "list_manual_adjustments",
    "list_card_adjustment_history",
    "list_card_revision_pick_changes",
    "list_contest_picks",
    "list_pick_audits",
    "list_pick_adjustment_items",
    "record_card_revision",
    "record_manual_adjustment",
    "record_model_prediction",
    "record_model_run",
    "record_pick_audit",
    "record_sportsbook_recommendation",
    "record_pick_adjustment_snapshot",
    "register_confidence_ranking_policy",
    "register_daily_refresh_policy",
    "register_manual_adjustment_policy",
    "refresh_full_card",
    "reproduce_card",
    "validate_full_card",
]
